"""Goals tool configuration for the AI agent.

This module defines the configuration for goal-related CRUD tools.
All tools are generated by the factory using this configuration.
"""

from pydantic import BaseModel

from src.agent.models import ToolDef
from src.agent.tools.factory import CRUDToolConfig, create_crud_tools
from src.agent.tools.models import AgentGoalCreateArgs, AgentGoalUpdateArgs
from src.agent.utils.templates import build_goal_content
from src.api.notion.goals.models import GoalQueryRequest
from src.notion.enums import GoalCategory, GoalStatus, Priority

# Build descriptions with enum options
_status_options = ", ".join(GoalStatus)
_priority_options = ", ".join(Priority)
_category_options = ", ".join(GoalCategory)


def _build_goal_content(args: BaseModel) -> str:
    """Build goal content from agent args."""
    description = getattr(args, "description", None)
    notes = getattr(args, "notes", None)
    return build_goal_content(description=description, notes=notes)


GOAL_TOOL_CONFIG = CRUDToolConfig(
    domain="goal",
    domain_plural="goals",
    endpoint_prefix="/notion/goals",
    id_field="goal_id",
    name_field="goal_name",
    query_model=GoalQueryRequest,
    create_model=AgentGoalCreateArgs,
    update_model=AgentGoalUpdateArgs,
    enum_fields={
        "status": GoalStatus,
        "priority": Priority,
        "category": GoalCategory,
    },
    tags=frozenset({"goals"}),
    content_builder=_build_goal_content,
    query_description=(
        f"Query goals from the goals tracker. Use name_filter for fuzzy search "
        f"by goal name (e.g. 'fitness' matches 'Improve fitness'). "
        f"By default excludes completed goals; set include_done=true to include them. "
        f"Can filter by status ({_status_options}), priority ({_priority_options}), "
        f"or category ({_category_options}). "
        f"Response includes fuzzy_match_quality ('good' or 'weak') - ask for clarification if 'weak'. "
        f"Does NOT return page content; use get_goal to retrieve a goal's content."
    ),
    get_description=(
        "Get details of a specific goal by its ID. "
        "Returns goal name, status, priority, progress, due date, "
        "and page content (in markdown format)."
    ),
    create_description=(
        f"Create a new goal. Required: goal_name. "
        f"BEFORE calling: check if goal_name is specific and measurable. "
        f"Too vague: 'Get fit', 'Learn coding', 'Save money'. "
        f"Better: 'Run a half marathon by June', 'Complete Python course', 'Save £5000 for holiday'. "
        f"If vague, ask the user for more details. "
        f"Title case the goal name. "
        f"Optional: description, notes, status ({_status_options}), "
        f"priority ({_priority_options}), category ({_category_options}), progress (0-100), due_date."
    ),
    update_description=(
        f"Update an existing goal. Requires the goal_id. "
        f"Can update goal name, status ({_status_options}), "
        f"priority ({_priority_options}), category ({_category_options}), progress, or due date. "
        f"IMPORTANT: Before updating description/notes, you MUST first call get_goal to retrieve "
        f"the current content, then merge existing content with your changes. The content field "
        f"will REPLACE all existing page content. If get_goal fails due to unsupported blocks, "
        f"inform the user they must edit directly in Notion."
    ),
)


def get_goals_tools() -> list[ToolDef]:
    """Get all goals tool definitions.

    :returns: List of ToolDef instances for goals operations.
    """
    return create_crud_tools(GOAL_TOOL_CONFIG)
