"""Goals tool configuration for the AI agent.

This module defines the configuration for goal-related CRUD tools.
All tools are generated by the factory using this configuration.
"""

from src.agent.models import ToolDef
from src.agent.tools.factory import CRUDToolConfig, create_crud_tools
from src.api.notion.goals.models import (
    GoalCreateRequest,
    GoalQueryRequest,
    GoalUpdateRequest,
)
from src.notion.enums import GoalStatus, Priority

# Build descriptions with enum options
_status_options = ", ".join(GoalStatus)
_priority_options = ", ".join(Priority)

GOAL_TOOL_CONFIG = CRUDToolConfig(
    domain="goal",
    domain_plural="goals",
    endpoint_prefix="/notion/goals",
    id_field="goal_id",
    query_model=GoalQueryRequest,
    create_model=GoalCreateRequest,
    update_model=GoalUpdateRequest,
    enum_fields={
        "status": GoalStatus,
        "priority": Priority,
    },
    tags=frozenset({"goals"}),
    query_description=(
        f"Query goals from the goals tracker. Use name_filter for fuzzy search "
        f"by goal name (e.g. 'fitness' matches 'Improve fitness'). "
        f"By default excludes completed goals; set include_done=true to include them. "
        f"Can also filter by status ({_status_options}) and priority ({_priority_options}). "
        f"Response includes fuzzy_match_quality ('good' or 'weak') - ask for clarification if 'weak'."
    ),
    get_description=(
        "Get details of a specific goal by its ID. "
        "Returns goal name, status, priority, progress, and due date."
    ),
    create_description=(
        f"Create a new goal. Requires a goal name. "
        f"Optional: status ({_status_options}), priority ({_priority_options}), "
        f"progress (0-100), and due date."
    ),
    update_description=(
        f"Update an existing goal. Requires the goal_id. "
        f"Can update goal name, status ({_status_options}), "
        f"priority ({_priority_options}), progress, or due date."
    ),
)


def get_goals_tools() -> list[ToolDef]:
    """Get all goals tool definitions.

    :returns: List of ToolDef instances for goals operations.
    """
    return create_crud_tools(GOAL_TOOL_CONFIG)
