"""Ideas tool configuration for the AI agent.

This module defines the configuration for ideas CRUD tools.
All tools are generated by the factory using this configuration.
"""

from pydantic import BaseModel

from src.agent.models import ToolDef
from src.agent.tools.factory import CRUDToolConfig, create_crud_tools
from src.agent.tools.models import AgentIdeaCreateArgs, AgentIdeaUpdateArgs
from src.agent.utils.templates import build_idea_content
from src.api.notion.ideas.models import IdeaQueryRequest
from src.notion.enums import IdeaGroup

# Build descriptions with enum options
_group_options = ", ".join(IdeaGroup)


def _build_idea_content(args: BaseModel) -> str:
    """Build idea content from agent args."""
    notes = getattr(args, "notes", None)
    return build_idea_content(notes=notes)


IDEAS_TOOL_CONFIG = CRUDToolConfig(
    domain="idea",
    domain_plural="ideas",
    endpoint_prefix="/notion/ideas",
    id_field="idea_id",
    query_model=IdeaQueryRequest,
    create_model=AgentIdeaCreateArgs,
    update_model=AgentIdeaUpdateArgs,
    enum_fields={
        "idea_group": IdeaGroup,
    },
    tags=frozenset({"ideas"}),
    content_builder=_build_idea_content,
    query_description=(
        f"Query ideas from the ideas tracker. Use name_filter for fuzzy search "
        f"by idea title (e.g. 'app' matches 'New mobile app idea'). "
        f"Can filter by idea_group ({_group_options}). "
        f"Response includes fuzzy_match_quality ('good' or 'weak') - ask for clarification if 'weak'. "
        f"Does NOT return page content; use get_idea to retrieve an idea's full details."
    ),
    get_description=(
        "Get details of a specific idea by its ID. "
        "Returns idea title, group, and page content (in markdown format)."
    ),
    create_description=(
        f"Create a new idea. Required: idea (descriptive title) and notes (details/context). "
        f"BEFORE calling: ensure both title AND notes have sufficient detail. "
        f"Title examples - Too vague: 'App idea', 'Project'. "
        f"Better: 'Mobile app for tracking daily habits with gamification'. "
        f"Notes must explain: what is the idea and any initial thoughts. "
        f"If the user only provides a brief mention, ask them to elaborate before creating. "
        f"Optional: idea_group ({_group_options})."
    ),
    update_description=(
        f"Update an existing idea. Requires the idea_id. "
        f"Can update idea (title), idea_group ({_group_options}). "
        f"Use notes to update page content; omit to keep existing."
    ),
)


def get_ideas_tools() -> list[ToolDef]:
    """Get all ideas tool definitions.

    :returns: List of ToolDef instances for ideas operations.
    """
    return create_crud_tools(IDEAS_TOOL_CONFIG)
