"""Projects tool configuration for the AI agent.

This module defines the configuration for project-related CRUD tools.
All tools are generated by the factory using this configuration.
"""

from pydantic import BaseModel

from src.agent.models import ToolDef
from src.agent.tools.factory import CRUDToolConfig, create_crud_tools
from src.agent.tools.models import AgentProjectCreateArgs, AgentProjectUpdateArgs
from src.agent.utils.templates import build_project_content
from src.api.notion.projects.models import ProjectQueryRequest
from src.notion.enums import ProjectGroup, ProjectPriority, ProjectStatus

# Build descriptions with enum options
_status_options = ", ".join(ProjectStatus)
_priority_options = ", ".join(ProjectPriority)
_group_options = ", ".join(ProjectGroup)


def _build_project_content(args: BaseModel) -> str:
    """Build project content from agent args."""
    description = getattr(args, "description", None)
    notes = getattr(args, "notes", None)
    return build_project_content(description=description, notes=notes)


PROJECT_TOOL_CONFIG = CRUDToolConfig(
    domain="project",
    domain_plural="projects",
    endpoint_prefix="/notion/projects",
    id_field="project_id",
    name_field="project_name",
    query_model=ProjectQueryRequest,
    create_model=AgentProjectCreateArgs,
    update_model=AgentProjectUpdateArgs,
    enum_fields={
        "status": ProjectStatus,
        "priority": ProjectPriority,
        "project_group": ProjectGroup,
    },
    tags=frozenset({"projects"}),
    content_builder=_build_project_content,
    query_description=(
        f"Query projects from the projects tracker. Use name_filter for fuzzy search "
        f"by project name (e.g. 'website' matches 'Website Redesign'). "
        f"By default excludes completed projects; set include_done=true to include them. "
        f"Can filter by status ({_status_options}), priority ({_priority_options}), "
        f"or project group ({_group_options}). "
        f"Response includes fuzzy_match_quality ('good' or 'weak') - ask for clarification if 'weak'. "
        f"Does NOT return page content; use get_project to retrieve a project's content."
    ),
    get_description=(
        "Get details of a specific project by its ID. "
        "Returns project name, status, priority, group, "
        "and page content (in markdown format)."
    ),
    create_description=(
        f"Create a new project. Required: project_name, project_group ({_group_options}). "
        f"Title case the project name. "
        f"Optional: description, notes, status ({_status_options}), "
        f"priority ({_priority_options})."
    ),
    update_description=(
        f"Update an existing project. Requires the project_id. "
        f"Can update project name, status ({_status_options}), "
        f"priority ({_priority_options}), or project group ({_group_options}). "
        f"IMPORTANT: Before updating description/notes, you MUST first call get_project to retrieve "
        f"the current content, then merge existing content with your changes. The content field "
        f"will REPLACE all existing page content. If get_project fails due to unsupported blocks, "
        f"inform the user they must edit directly in Notion."
    ),
)


def get_projects_tools() -> list[ToolDef]:
    """Get all project tool definitions.

    :returns: List of ToolDef instances for project operations.
    """
    return create_crud_tools(PROJECT_TOOL_CONFIG)
