"""Reading list tool configuration for the AI agent.

This module defines the configuration for reading list CRUD tools.
All tools are generated by the factory using this configuration.
"""

from pydantic import BaseModel

from src.agent.models import ToolDef
from src.agent.tools.factory import CRUDToolConfig, create_crud_tools
from src.agent.tools.models import AgentReadingItemCreateArgs, AgentReadingItemUpdateArgs
from src.agent.utils.templates import build_reading_item_content
from src.api.notion.reading_list.models import ReadingQueryRequest
from src.notion.enums import Priority, ReadingCategory, ReadingStatus, ReadingType

# Build descriptions with enum options
_type_options = ", ".join(ReadingType)
_status_options = ", ".join(ReadingStatus)
_category_options = ", ".join(ReadingCategory)
_priority_options = ", ".join(Priority)


def _build_reading_content(args: BaseModel) -> str:
    """Build reading item content from agent args."""
    notes = getattr(args, "notes", None)
    return build_reading_item_content(notes=notes)


READING_LIST_TOOL_CONFIG = CRUDToolConfig(
    domain="reading_item",
    domain_plural="reading_list",
    endpoint_prefix="/notion/reading-list",
    id_field="item_id",
    name_field="title",
    query_model=ReadingQueryRequest,
    create_model=AgentReadingItemCreateArgs,
    update_model=AgentReadingItemUpdateArgs,
    enum_fields={
        "item_type": ReadingType,
        "status": ReadingStatus,
        "category": ReadingCategory,
        "priority": Priority,
    },
    tags=frozenset({"reading"}),
    content_builder=_build_reading_content,
    query_description=(
        f"Query items from the reading list. Use name_filter for fuzzy search "
        f"by title (e.g. 'clean code' matches 'Clean Code book'). "
        f"By default excludes completed items; set include_completed=true to include them. "
        f"Can also filter by type ({_type_options}), status ({_status_options}), "
        f"category ({_category_options}), and priority ({_priority_options}). "
        f"Response includes fuzzy_match_quality ('good' or 'weak') - ask for clarification if 'weak'. "
        f"Does NOT return page content; use get_reading_item to retrieve an item's content."
    ),
    get_description=(
        "Get details of a specific reading list item by its ID. "
        "Returns title, type (Book, Article, Other), status, priority, category, "
        "item_url (article/resource link), and page content (in markdown format)."
    ),
    create_description=(
        f"Create a new reading list item. Required: title and item_type ({_type_options}). "
        f"BEFORE calling: check if title is the actual book/article name. "
        f"Too vague: 'Article', 'Book', 'Blog post'. "
        f"Better: 'Clean Code by Robert Martin', 'React hooks tutorial', 'NYT article on AI'. "
        f"If vague, ask the user for the title or URL. "
        f"Optional: notes, item_url (article/resource URL), status ({_status_options}), "
        f"priority ({_priority_options}), category ({_category_options})."
    ),
    update_description=(
        f"Update an existing reading list item. Requires the item_id. "
        f"Can update title, type ({_type_options}), status ({_status_options}), "
        f"priority ({_priority_options}), category ({_category_options}), or item_url. "
        f"Use notes to update page content; omit to keep existing."
    ),
)


def get_reading_list_tools() -> list[ToolDef]:
    """Get all reading list tool definitions.

    :returns: List of ToolDef instances for reading list operations.
    """
    return create_crud_tools(READING_LIST_TOOL_CONFIG)
