"""Reading list tool configuration for the AI agent.

This module defines the configuration for reading list CRUD tools.
All tools are generated by the factory using this configuration.
"""

from src.agent.models import ToolDef
from src.agent.tools.factory import CRUDToolConfig, create_crud_tools
from src.api.notion.reading_list.models import (
    ReadingItemCreateRequest,
    ReadingItemUpdateRequest,
    ReadingQueryRequest,
)
from src.notion.enums import Priority, ReadingCategory, ReadingStatus

# Build descriptions with enum options
_status_options = ", ".join(ReadingStatus)
_category_options = ", ".join(ReadingCategory)
_priority_options = ", ".join(Priority)

READING_LIST_TOOL_CONFIG = CRUDToolConfig(
    domain="reading_item",
    domain_plural="reading_list",
    endpoint_prefix="/notion/reading-list",
    id_field="item_id",
    query_model=ReadingQueryRequest,
    create_model=ReadingItemCreateRequest,
    update_model=ReadingItemUpdateRequest,
    enum_fields={
        "status": ReadingStatus,
        "category": ReadingCategory,
        "priority": Priority,
    },
    tags=frozenset({"reading"}),
    query_description=(
        f"Query items from the reading list. Use name_filter for fuzzy search "
        f"by title (e.g. 'clean code' matches 'Clean Code book'). "
        f"By default excludes completed items; set include_completed=true to include them. "
        f"Can also filter by status ({_status_options}), category ({_category_options}), "
        f"and priority ({_priority_options}). "
        f"Response includes fuzzy_match_quality ('good' or 'weak') - ask for clarification if 'weak'."
    ),
    get_description=(
        "Get details of a specific reading list item by its ID. "
        "Returns title, status, priority, category, URL, and read date."
    ),
    create_description=(
        f"Create a new item in the reading list. Requires a title. "
        f"Optional: status ({_status_options}), priority ({_priority_options}), "
        f"category ({_category_options}), and item URL."
    ),
    update_description=(
        f"Update an existing reading list item. Requires the item_id. "
        f"Can update title, status ({_status_options}), priority ({_priority_options}), "
        f"category ({_category_options}), URL, or read date."
    ),
)


def get_reading_list_tools() -> list[ToolDef]:
    """Get all reading list tool definitions.

    :returns: List of ToolDef instances for reading list operations.
    """
    return create_crud_tools(READING_LIST_TOOL_CONFIG)
