"""Tasks tool configuration for the AI agent.

This module defines the configuration for task-related CRUD tools.
All tools are generated by the factory using this configuration.
"""

from src.agent.models import ToolDef
from src.agent.tools.factory import CRUDToolConfig, create_crud_tools
from src.api.notion.tasks.models import (
    TaskCreateRequest,
    TaskQueryRequest,
    TaskUpdateRequest,
)
from src.notion.enums import EffortLevel, Priority, TaskGroup, TaskStatus

# Build descriptions with enum options
_status_options = ", ".join(TaskStatus)
_priority_options = ", ".join(Priority)
_effort_options = ", ".join(EffortLevel)
_group_options = ", ".join(TaskGroup)

TASK_TOOL_CONFIG = CRUDToolConfig(
    domain="task",
    domain_plural="tasks",
    endpoint_prefix="/notion/tasks",
    id_field="task_id",
    query_model=TaskQueryRequest,
    create_model=TaskCreateRequest,
    update_model=TaskUpdateRequest,
    enum_fields={
        "status": TaskStatus,
        "priority": Priority,
        "effort": EffortLevel,
        "group": TaskGroup,
    },
    tags=frozenset({"tasks"}),
    query_description=(
        f"Query tasks from the task tracker. Use name_filter for fuzzy search "
        f"by task name (e.g. 'email' matches 'Read emails'). "
        f"By default excludes completed tasks; set include_done=true to include them. "
        f"Can filter by status ({_status_options}), priority ({_priority_options}), "
        f"effort level ({_effort_options}), and task group ({_group_options}). "
        f"Response includes fuzzy_match_quality ('good' or 'weak') - ask for clarification if 'weak'."
    ),
    get_description=(
        "Get details of a specific task by its ID. "
        "Returns task name, status, due date, priority, effort level, and task group."
    ),
    create_description=(
        f"Create a new task. Requires a task name, task group ({_group_options}), and due date. "
        f"Optional: status ({_status_options}), priority ({_priority_options}), "
        f"and effort level ({_effort_options})."
    ),
    update_description=(
        f"Update an existing task. Requires the task_id. "
        f"Can update task name, status ({_status_options}), priority ({_priority_options}), "
        f"effort level ({_effort_options}), task group ({_group_options}), or due date."
    ),
)


def get_tasks_tools() -> list[ToolDef]:
    """Get all tasks tool definitions.

    :returns: List of ToolDef instances for tasks operations.
    """
    return create_crud_tools(TASK_TOOL_CONFIG)
