"""Tasks tool configuration for the AI agent.

This module defines the configuration for task-related CRUD tools.
All tools are generated by the factory using this configuration.
"""

from pydantic import BaseModel

from src.agent.models import ToolDef
from src.agent.tools.factory import CRUDToolConfig, create_crud_tools
from src.agent.tools.models import AgentTaskCreateArgs, AgentTaskUpdateArgs
from src.agent.utils.templates import build_task_content
from src.api.notion.tasks.models import TaskQueryRequest
from src.notion.enums import EffortLevel, Priority, TaskGroup, TaskStatus

# Build descriptions with enum options
_status_options = ", ".join(TaskStatus)
_priority_options = ", ".join(Priority)
_effort_options = ", ".join(EffortLevel)
_group_options = ", ".join(TaskGroup)


def _build_task_content(args: BaseModel) -> str:
    """Build task content from agent args."""
    description = getattr(args, "description", None)
    notes = getattr(args, "notes", None)
    return build_task_content(description=description, notes=notes)


TASK_TOOL_CONFIG = CRUDToolConfig(
    domain="task",
    domain_plural="tasks",
    endpoint_prefix="/notion/tasks",
    id_field="task_id",
    name_field="task_name",
    query_model=TaskQueryRequest,
    create_model=AgentTaskCreateArgs,
    update_model=AgentTaskUpdateArgs,
    enum_fields={
        "status": TaskStatus,
        "priority": Priority,
        "effort": EffortLevel,
        "group": TaskGroup,
    },
    tags=frozenset({"tasks"}),
    content_builder=_build_task_content,
    query_description=(
        f"Query tasks from the task tracker. Use name_filter for fuzzy search "
        f"by task name (e.g. 'email' matches 'Read emails'). "
        f"By default excludes completed tasks; set include_done=true to include them. "
        f"Can filter by status ({_status_options}), priority ({_priority_options}), "
        f"effort level ({_effort_options}), and task group ({_group_options}). "
        f"Response includes fuzzy_match_quality ('good' or 'weak') - ask for clarification if 'weak'. "
        f"Does NOT return page content; use get_task to retrieve a task's content."
    ),
    get_description=(
        "Get details of a specific task by its ID. "
        "Returns task name, status, due date, priority, effort level, task group, "
        "and page content (in markdown format)."
    ),
    create_description=(
        f"Create a new task. Required: task_name, task_group ({_group_options}), due_date. "
        f"BEFORE calling: check if task_name is specific enough to find later. "
        f"Too vague: 'Send email', 'Meeting', 'Call'. "
        f"Better: 'Send Q4 report to finance', 'Team standup', 'Call John re: project'. "
        f"If vague, ask the user for more details. "
        f"Title case the task name. For high effort tasks, add a description. "
        f"Optional: description, notes, status ({_status_options}), "
        f"priority ({_priority_options}), effort ({_effort_options})."
    ),
    update_description=(
        f"Update an existing task. Requires the task_id. "
        f"Can update task name, status ({_status_options}), priority ({_priority_options}), "
        f"effort level ({_effort_options}), task group ({_group_options}), or due date. "
        f"Use description/notes to update page content; omit to keep existing."
    ),
)


def get_tasks_tools() -> list[ToolDef]:
    """Get all tasks tool definitions.

    :returns: List of ToolDef instances for tasks operations.
    """
    return create_crud_tools(TASK_TOOL_CONFIG)
