"""add agent tracking tables

Revision ID: 03cc9dfa944e
Revises: b67205ca72e9
Create Date: 2025-12-25 18:40:58.305033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03cc9dfa944e'
down_revision: Union[str, Sequence[str], None] = 'b67205ca72e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('total_estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_conversations_external_id', 'conversations', ['external_id'], unique=False)
    op.create_index('idx_conversations_started_at', 'conversations', ['started_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('stop_reason', sa.String(length=50), nullable=False),
    sa.Column('steps_taken', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('total_estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_runs_conversation_id', 'agent_runs', ['conversation_id'], unique=False)
    op.create_index('idx_agent_runs_started_at', 'agent_runs', ['started_at'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('model_alias', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('call_type', sa.String(length=50), nullable=False),
    sa.Column('request_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_calls_agent_run_id', 'llm_calls', ['agent_run_id'], unique=False)
    op.create_index('idx_llm_calls_called_at', 'llm_calls', ['called_at'], unique=False)
    op.create_index('idx_llm_calls_model_alias', 'llm_calls', ['model_alias'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_llm_calls_model_alias', table_name='llm_calls')
    op.drop_index('idx_llm_calls_called_at', table_name='llm_calls')
    op.drop_index('idx_llm_calls_agent_run_id', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('idx_agent_runs_started_at', table_name='agent_runs')
    op.drop_index('idx_agent_runs_conversation_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('idx_conversations_started_at', table_name='conversations')
    op.drop_index('idx_conversations_external_id', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
