"""Add agent memory tables

Revision ID: 1e15f73f876a
Revises: b37b23c6ba1e
Create Date: 2026-01-11 17:42:02.276599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e15f73f876a'
down_revision: Union[str, Sequence[str], None] = 'b37b23c6ba1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_memories_category', 'agent_memories', ['category'], unique=False)
    op.create_index('idx_agent_memories_deleted_at', 'agent_memories', ['deleted_at'], unique=False)
    op.create_index('idx_agent_memories_subject', 'agent_memories', ['subject'], unique=False)
    op.create_table('agent_memory_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.String(length=8), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_conversation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['agent_memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['agent_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_versions_created_at', 'agent_memory_versions', ['created_at'], unique=False)
    op.create_index('idx_memory_versions_memory_id', 'agent_memory_versions', ['memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_memory_versions_memory_id', table_name='agent_memory_versions')
    op.drop_index('idx_memory_versions_created_at', table_name='agent_memory_versions')
    op.drop_table('agent_memory_versions')
    op.drop_index('idx_agent_memories_subject', table_name='agent_memories')
    op.drop_index('idx_agent_memories_deleted_at', table_name='agent_memories')
    op.drop_index('idx_agent_memories_category', table_name='agent_memories')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
