"""Add Telegram session tracking tables

Revision ID: 2b07155adfe9
Revises: 05c15250d222
Create Date: 2025-12-26 23:46:51.593088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b07155adfe9'
down_revision: Union[str, Sequence[str], None] = '05c15250d222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_polling_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('agent_conversation_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_conversation_id'], ['agent_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telegram_sessions_chat_id_active', 'telegram_sessions', ['chat_id', 'is_active'], unique=False)
    op.create_index('idx_telegram_sessions_last_activity', 'telegram_sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_telegram_sessions_chat_id'), 'telegram_sessions', ['chat_id'], unique=False)
    op.create_table('telegram_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telegram_messages_created_at', 'telegram_messages', ['created_at'], unique=False)
    op.create_index('idx_telegram_messages_session_id', 'telegram_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telegram_messages_session_id', table_name='telegram_messages')
    op.drop_index('idx_telegram_messages_created_at', table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_index(op.f('ix_telegram_sessions_chat_id'), table_name='telegram_sessions')
    op.drop_index('idx_telegram_sessions_last_activity', table_name='telegram_sessions')
    op.drop_index('idx_telegram_sessions_chat_id_active', table_name='telegram_sessions')
    op.drop_table('telegram_sessions')
    op.drop_table('telegram_polling_cursor')
    # ### end Alembic commands ###
