"""Simplifying model v2

Revision ID: 3453c4fca5d9
Revises: 39165b91be18
Create Date: 2025-12-21 17:35:20.554394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3453c4fca5d9'
down_revision: Union[str, Sequence[str], None] = '39165b91be18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'source_publication')
    op.drop_column('articles', 'section')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('section', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('source_publication', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
