"""Simplifying model

Revision ID: 39165b91be18
Revises: 9bc77132067d
Create Date: 2025-12-21 16:58:28.589900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39165b91be18'
down_revision: Union[str, Sequence[str], None] = '9bc77132067d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'section',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.drop_column('articles', 'position_in_newsletter')
    op.drop_column('newsletters', 'article_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('article_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('position_in_newsletter', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('articles', 'section',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
