"""Create newsletters and articles tables

Revision ID: 9bc77132067d
Revises: 
Create Date: 2025-12-21 16:29:01.259237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc77132067d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=False),
    sa.Column('newsletter_type', sa.Enum('TLDR', 'TLDR_AI', 'TLDR_DEV', name='newsletter_type_enum'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_index('idx_newsletters_received_at', 'newsletters', ['received_at'], unique=False)
    op.create_index('idx_newsletters_type', 'newsletters', ['newsletter_type'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('newsletter_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('source_publication', sa.String(length=200), nullable=True),
    sa.Column('position_in_newsletter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_articles_newsletter_id', 'articles', ['newsletter_id'], unique=False)
    op.create_index('idx_articles_url_hash', 'articles', ['url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_articles_url_hash', table_name='articles')
    op.drop_index('idx_articles_newsletter_id', table_name='articles')
    op.drop_table('articles')
    op.drop_index('idx_newsletters_type', table_name='newsletters')
    op.drop_index('idx_newsletters_received_at', table_name='newsletters')
    op.drop_table('newsletters')
    # ### end Alembic commands ###
